server:
  port: 8082 # Puerto único para este microservicio

spring:
  application:
    name: batch-management-context

  datasource:
    url: jdbc:mysql://127.0.0.1:3307/batch_management_db
    username: foodchain_user
    password: foodchain_password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: foodchain
    password: foodchain

api:
  clients:
    iam-service:
      base-url: "http://localhost:8081/api/v1/iam/auth" # URL base para el servicio de identidad

openapi:
  service:
    title: "FoodChain - Batch Management Service API"
    version: "v1.0.0"
    description: "API para la gestión del ciclo de vida de lotes en la plataforma FoodChain."