# ======================================================\n# === API GATEWAY CONFIGURATION                      ===\n# ======================================================
server:
  port: 8080

spring:
  application:
    name: api-gateway

---
# ======================================================
#  === PERFIL DE DESARROLLO LOCAL (default)          ===
#  =====================================================
spring:
  config:
    activate:
      on-profile: "default"
  cloud:
    gateway:
      routes:
        - id: identity-context-route
          uri: http://localhost:8081 # Apunta al servicio corriendo en local
          predicates:
            - Path=/api/v1/iam/** # CUALQUIER petici√≥n a /api/v1/iam/...

        - id: batch-management-context-route
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/batches/**

        - id: traceability-context-route
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/trace/**

---
# ======================================================
# === PERFIL DOCKER                                  ===
# ======================================================
spring:
  config:
    activate:
      on-profile: "docker"
  cloud:
    gateway:
      # usamos el enrutamiento directo por hostname.
      routes:
        - id: identity-context-route
          uri: http://identity-context:8081
          predicates:
            - Path=/api/v1/iam/**

        - id: batch-management-context-route
          uri: http://batch-management-context:8082
          predicates:
            - Path=/api/v1/batches/**

        - id: traceability-context-route
          uri: http://traceability-context:8083
          predicates:
            - Path=/api/v1/trace/**